### ISSUE TITLE
All requests that reach pods have the load balancer's IP

### ISSUE THREAD

**Issue by milosmns** [k3s-io/klipper-lb#31]
Hey, to avoid copy-pasting the same question, here's the [StackOverflow link](https://stackoverflow.com/questions/70356717/nginx-ingress-controllers-load-balancer-is-hiding-the-real-client-ip/70363420#70363420).

Basically I want my pods to get the original client IP address... or at least have `X-Forwarded-For` header, in a worse-case scenario.

As I said there, happy to share more details to get this sorted out.

**Comment by mamiu** [comment]
I guess you're using [k3s](https://k3s.io/) as Kubernetes distribution and probably [Traefik](https://traefik.io/traefik/) as your cluster router (default router for k3s).

If you're using Traefik, here's how you get the original client IP address (for other routers, the settings may be a bit different, but the same logic still applies):

1. Set `externalTrafficPolicy` to `Local`. If you use the [Traefik helm chart](https://github.com/traefik/traefik-helm-chart/tree/master/traefik) you can set the values to:

   ```yaml
    service:
      spec:
        externalTrafficPolicy: Local
   ```

2. If you have multiple nodes make sure that your router is running on the node where you send the traffic to. Let's say you have the domain `example.com` and that is pointing to your cluster node with the IP 123.4.5.67 (e.g. with an DNS A record) then make sure that your router is running on that exact node. In the Traefik helm chart you can do this with the `nodeAffinity` config:

   ```yaml
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: [ "node2" ]
   ```

   You could even have multiple nodes in your `nodeAffinity` list with different weights (the higher the weight the more likely it will be deployed on that node):

   ```yaml
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 20
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: [ "node1" ]
          - weight: 10
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values: [ "node2" ]
   ```

   Just replace the node name in the values array and adjust the weight to your needs.

   To get the `kubernetes.io/hostname` label for each of your nodes you can run this command (in most cases the node name and `kubernetes.io/hostname` label are identical):

   ```bash
   kubectl get nodes -o custom-columns="NAME:.metadata.name,LABEL (kubernetes.io/hostname):{.metadata.labels.kubernetes\.io/hostname}"
   ```


For more details have a look at this article: [K3S Thing: Make Traefik Forward Real Client IP](https://comphilip.wordpress.com/2021/05/23/k3s-thing-make-traefik-forward-real-client-ip/)  
The only problem with that article is that it only offers a `DaemonSet` as solution (instead of the default deployment of kind `Deployment`) which prevents the user from using Traefik to generate SSL certificates (acme certificate resolvers in Traefik are [only available](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/daemonset.yaml#L5) in `Deployment` mode).

**Comment by milosmns** [comment]
As per the guide's 3rd step, I disabled Traefik and was using Nginx Ingress Controller

**Comment by mamiu** [comment]
Ah sorry, I didn't read that guide. But you can still use my answer to fix your problem. Just make sure that `externalTrafficPolicy` is set to `Local` (as [documented here](https://kubernetes.github.io/ingress-nginx/deploy/#cloud-deployments) for nginx) and your nodeAffinity is set as described in my comment above ([here's](https://github.com/kubernetes/ingress-nginx/blob/a43346d975a6350f48e5420782e5051b7805e106/charts/ingress-nginx/values.yaml#L229-L268) how you set the affinity in the nginx helm chart).

**Comment by Taymindis** [comment]
I am running one node. Set To local still getting `svclb` ip. I think it's a bug?

**Comment by mamiu** [comment]
@Taymindis Where and how did you set the externalTrafficPolicy to Local? Because if you do it at runtime you have to restart Traefik. And how do you check it? With the whoami container from containous?

**Comment by Taymindis** [comment]
> @Taymindis Where and how did you set the externalTrafficPolicy to Local? Because if you do it at runtime you have to restart Traefik. And how do you check it? With the whoami container from containous?

Hi @mamiu , I am running bare-metal k3s without `traefik` on ubuntu vm.

My Steps of procedure 
- Uninstall Ingress-nginx from Helm
- Reinstall helm again with update values.yaml to `Local`
- 
```yaml
  service:
    enabled: true

    # -- If enabled is adding an appProtocol option for Kubernetes service. An appProtocol field replacing annotations that were
    # using for setting a backend protocol. Here is an example for AWS: service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # It allows choosing the protocol for each backend specified in the Kubernetes service.
    # See the following GitHub issue for more details about the purpose: https://github.com/kubernetes/kubernetes/issues/40244
    # Will be ignored for Kubernetes versions older than 1.20
    ##
    appProtocol: true

    annotations: {}
    labels: {}
    # clusterIP: ""

    # -- List of IP addresses at which the controller services are available
    ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
    ##
    externalIPs: []

    # loadBalancerIP: ""
    loadBalancerSourceRanges: []

    enableHttp: true
    enableHttps: true

    ## Set external traffic policy to: "Local" to preserve source IP on providers supporting it.
    ## Ref: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-typeloadbalancer
    externalTrafficPolicy: "Local"
```

And I have a app pod which echo back the client IP back when we service a specific url.

Please note that I am not using `traefik`, I am using `kubernetes/ingress-nginx`
